# site details
title: shxdow's blog
# tag_line: Y
description: I obsess over ones and zeros
# keywords: simple jekyll theme
url: https://shxdow.github.io/
author: shxdow
# author_url:
# email_subscribe: http://eepurl.com/cNZfVz

# tech
markdown: kramdown

