# Site settings
title: "shxdow"
blogtitle: "shxdow's research notes"
description: > 
  Write a description of your website here.

author: Alpha Toure
email: johnny@appleseed.com
twitter_username: imshxdow
github_username: shxdow

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shxdow.me" # the base hostname & protocol for your site

# google_analytics_id: UA-1111111111-1
# disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /blog/:title

sass:
    style: compressed

exclude: [vendor]

