# Site settings
title: "shxdow"
blogtitle: "shxdow's research notebook"
description: > 
  shxdow's research notebook

author: shxdow
email: alpha.tpa@gmail.com
twitter_username: shxdowtc
mastodon_username: shxdow
matrix_username: imshxdow\:matrix.org
github_username: shxdow

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shxdow.me" # the base hostname & protocol for your site

# google_analytics_id: UA-1111111111-1
# disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false

permalink: /blog/:title

sass:
    style: compressed

exclude: [vendor]

