# Basic
name:               "shxdow"
description:        "I'm obsessed with taking things apart  ¯\\_(ツ)_/¯"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//shxdow.github.io"
author:             "shxdow"
twitter:
  username:         "imshxdow"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
#permalink:          /:year/:month/:day/:title/
permalink:          /:title

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//shxdow.github.io/about"
  # - name:           "Download"
  #   href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
