# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: shxdow
email: dysonfrost@protonmail.ch
description: A never ending journey in the inner workings of computers
# description: Exploitation, reverse engineering and malware
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shxdow.github.io" # the base hostname & protocol for your site
twitter_username: imshxdow
github_username:  shxdow
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
