description: >
    I'm obsessed with taking things apart.

# master_repo: false
url: "https://shxdow.me"
markdown: kramdown
highlighter: rouge

permalink: /:title/

# plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed', 'jekyll-toc']
plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

rtl: false
name: shxdow
owner:
  email:   "shxdow@pm.me"
  twitter: imshxdow
  github:  https://github.com/shxdow
